; Docker php ini file
; Custom PHP settings
variables_order = "GPCS"

; Error Reporting
display_errors = On
error_reporting = E_ALL

; Memory Limit
memory_limit = 256M

; File Uploads
file_uploads = On
upload_max_filesize = 100M
post_max_size = 100M

; Session Settings
session.save_path = "/tmp"
session.gc_maxlifetime = 1440

; Time Zone
date.timezone = "America/Chicago"

; Execution Time
max_execution_time = 300