export type Payment = {
    id: string;
    amount: string;
    fee: string;
    net: string;
    created_at: string;
    name: string;
    email: string;
    giving_source: string;
    method: string;
    manual_trx_type: null | string;
    status: string;
    transaction_detail: null | string;
    subscription: string | null;
    status_ach: null | string;
    src: string;
    fund: string;
    subcreated_at: string;
    substart_on: string;
    subfrequency: string;
    substatus: string;
    trx_ret_id: null | string;
    trx_retorigin_id: null | string;
    manual_failed: null | string;
    is_fee_covered: "0" | "1";
    trx_type: string;
    epicpay_transaction_id: string;
    fts_status_id: string;
    _fts_status_label: string;
    _receipt_file_url:string;
};
